name: Lab4 CI Pipeline

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run CI test
        run: echo "Lab4 CI Pipeline is working successfully!"

      - name: Check application environment
        run: echo "Application environment is $APP_ENVIRONMENT"
        env:
          APP_ENVIRONMENT: ${{ secrets.APP_ENVIRONMENT }}